# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lfx-v2-query-service
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: >-
        Host(`{{.Values.ingress.hostname}}`) && PathPrefix(`/query/`)
      priority: 10
      middlewares:
        {{- if .Values.heimdall.enabled }}
        - name: heimdall
        {{- end }}
      services:
        - kind: Service
          name: lfx-v2-query-service
          port: web
