# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{/*
Generate or lookup existing secrets for lfx-v2-query-service
*/}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.secret.name -}}
{{- $pageTokenSecret := randAlphaNum 32 -}}
{{- if $existingSecret -}}
  {{- $pageTokenSecret = $existingSecret.data.PAGE_TOKEN_SECRET | b64dec -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # The PAGE_TOKEN_SECRET will be base64 encoded automatically by Helm
  # Priority order:
  # 1. Value from values.yaml (pageTokenSecret)
  # 2. Existing secret value (preserved across upgrades)
  # 3. Newly generated random value (only for first deployment)
  PAGE_TOKEN_SECRET: {{ .Values.secret.pageTokenSecret | default $pageTokenSecret | b64enc | quote }} 
