# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v1
kind: Service
metadata:
  name: lfx-v2-query-service
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: lfx-v2-query-service
