# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---:
replicaCount: 3

# Override from CLI/CI: --set image.tag=<git-sha>, etc.
image:
  tag: "0.1.0"
  repository: linuxfoundation/lfx-query-svc
