openapi: 3.0.3
info:
    title: LFX V2 - Query Service
    description: Query indexed resources
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for lfx-v2-query-service
paths:
    /_query/openapi.json:
        get:
            tags:
                - query-svc
            summary: Download gen/http/openapi.json
            operationId: query-svc#/_query/openapi.json
            responses:
                "200":
                    description: File downloaded
    /_query/openapi.yaml:
        get:
            tags:
                - query-svc
            summary: Download gen/http/openapi.yaml
            operationId: query-svc#/_query/openapi.yaml
            responses:
                "200":
                    description: File downloaded
    /_query/openapi3.json:
        get:
            tags:
                - query-svc
            summary: Download gen/http/openapi3.json
            operationId: query-svc#/_query/openapi3.json
            responses:
                "200":
                    description: File downloaded
    /_query/openapi3.yaml:
        get:
            tags:
                - query-svc
            summary: Download gen/http/openapi3.yaml
            operationId: query-svc#/_query/openapi3.yaml
            responses:
                "200":
                    description: File downloaded
    /query/resources:
        get:
            tags:
                - query-svc
            summary: query-resources query-svc
            description: Locate resources by their type or parent, or use typeahead search to query resources by a display name or similar alias.
            operationId: query-svc#query-resources
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Version of the API
                    example: "1"
                    enum:
                        - "1"
                  example: "1"
                - name: name
                  in: query
                  description: Resource name or alias; supports typeahead
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Resource name or alias; supports typeahead
                    example: gov board
                    minLength: 1
                  example: gov board
                - name: parent
                  in: query
                  description: Parent (for navigation; varies by object type)
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Parent (for navigation; varies by object type)
                    example: project:123
                    pattern: ^[a-zA-Z]+:[a-zA-Z0-9_-]+$
                  example: project:123
                - name: type
                  in: query
                  description: Resource type to search
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Resource type to search
                    example: committee
                  example: committee
                - name: tags
                  in: query
                  description: Tags to search (varies by object type)
                  allowEmptyValue: true
                  schema:
                    type: array
                    items:
                        type: string
                        example: Tempore consequatur est architecto harum in.
                    description: Tags to search (varies by object type)
                    example:
                        - active
                  example:
                    - active
                - name: sort
                  in: query
                  description: Sort order for results
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Sort order for results
                    default: name_asc
                    example: updated_desc
                    enum:
                        - name_asc
                        - name_desc
                        - updated_asc
                        - updated_desc
                  example: updated_desc
                - name: page_token
                  in: query
                  description: Opaque token for pagination
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Opaque token for pagination
                    example: '****'
                  example: '****'
            responses:
                "200":
                    description: OK response.
                    headers:
                        Cache-Control:
                            description: Cache control header
                            schema:
                                type: string
                                description: Cache control header
                                example: public, max-age=300
                            example: public, max-age=300
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/QueryResourcesResponseBody'
                            example:
                                page_token: '****'
                                resources:
                                    - data:
                                        id: "123"
                                        name: My committee
                                        description: a committee
                                      id: "123"
                                      type: committee
                                    - data:
                                        id: "123"
                                        name: My committee
                                        description: a committee
                                      id: "123"
                                      type: committee
                                    - data:
                                        id: "123"
                                        name: My committee
                                        description: a committee
                                      id: "123"
                                      type: committee
                "400":
                    description: 'BadRequest: Bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                message: The request was invalid.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalServerError'
                            example:
                                message: An internal server error occurred.
                "503":
                    description: 'ServiceUnavailable: Service unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                message: The service is unavailable.
            security:
                - jwt_header_Authorization: []
components:
    schemas:
        BadRequestError:
            type: object
            properties:
                message:
                    type: string
                    description: Error message
                    example: The request was invalid.
            example:
                message: The request was invalid.
            required:
                - message
        InternalServerError:
            type: object
            properties:
                message:
                    type: string
                    description: Error message
                    example: An internal server error occurred.
            example:
                message: An internal server error occurred.
            required:
                - message
        QueryResourcesResponseBody:
            type: object
            properties:
                page_token:
                    type: string
                    description: Opaque token if more results are available
                    example: '****'
                resources:
                    type: array
                    items:
                        $ref: '#/components/schemas/Resource'
                    description: Resources found
                    example:
                        - data:
                            id: "123"
                            name: My committee
                            description: a committee
                          id: "123"
                          type: committee
                        - data:
                            id: "123"
                            name: My committee
                            description: a committee
                          id: "123"
                          type: committee
                        - data:
                            id: "123"
                            name: My committee
                            description: a committee
                          id: "123"
                          type: committee
                        - data:
                            id: "123"
                            name: My committee
                            description: a committee
                          id: "123"
                          type: committee
            example:
                page_token: '****'
                resources:
                    - data:
                        id: "123"
                        name: My committee
                        description: a committee
                      id: "123"
                      type: committee
                    - data:
                        id: "123"
                        name: My committee
                        description: a committee
                      id: "123"
                      type: committee
                    - data:
                        id: "123"
                        name: My committee
                        description: a committee
                      id: "123"
                      type: committee
                    - data:
                        id: "123"
                        name: My committee
                        description: a committee
                      id: "123"
                      type: committee
            required:
                - resources
        Resource:
            type: object
            properties:
                data:
                    description: Resource data snapshot
                    example:
                        id: "123"
                        name: My committee
                        description: a committee
                id:
                    type: string
                    description: Resource ID (within its resource collection)
                    example: "123"
                type:
                    type: string
                    description: Resource type
                    example: committee
            description: A resource is a universal representation of an LFX API resource for indexing.
            example:
                data:
                    id: "123"
                    name: My committee
                    description: a committee
                id: "123"
                type: committee
        ServiceUnavailableError:
            type: object
            properties:
                message:
                    type: string
                    description: Error message
                    example: The service is unavailable.
            example:
                message: The service is unavailable.
            required:
                - message
        Sortable:
            type: object
            properties:
                page_token:
                    type: string
                    description: Opaque token for pagination
                    example: '****'
                sort:
                    type: string
                    description: Sort order for results
                    default: name_asc
                    example: updated_desc
                    enum:
                        - name_asc
                        - name_desc
                        - updated_asc
                        - updated_desc
            example:
                page_token: '****'
                sort: updated_desc
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Heimdall authorization
            scheme: bearer
tags:
    - name: query-svc
      description: The query service provides resource and user queries.
