# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
replicaCount: 1

# Override from CLI/CI: --set image.tag=<git-sha>, etc.
image:
  repository: ghcr.io/linuxfoundation/lfx-v2-query-service/cmd
  tag: ""
  pullPolicy: IfNotPresent

# app is the configuration for the application
app:
  # use_oidc_contextualizer is a boolean to determine if the OIDC contextualizer should be used
  use_oidc_contextualizer: true
  # environment is the configuration for the application environment
  environment:
    OPENSEARCH_URL:
      value: http://opensearch-cluster-master:9200
    NATS_URL:
      value: nats://lfx-platform-nats.lfx.svc.cluster.local:4222
    JWKS_URL:
      value: http://lfx-platform-heimdall:4457/.well-known/jwks
    JWT_SIGNATURE_ALGORITHM:
      value: PS256
    PAGE_TOKEN_SECRET:
      valueFrom:
        secretKeyRef:
          name: lfx-v2-query-service-secrets
          key: PAGE_TOKEN_SECRET
    # CLEARBIT_CREDENTIAL is optional
    CLEARBIT_CREDENTIAL:
      value: null

# traefik is the configuration for Traefik Gateway API routing
traefik:
  # gateway specifies the platform Gateway to attach to
  gateway:
    name: lfx-platform-gateway
    namespace: lfx

# lfx is the configuration for LFX platform
lfx:
  # domain is the base domain for routing
  domain: k8s.orb.local
  # namespace is the target namespace for deployment
  namespace: lfx

# service is the configuration for the Kubernetes service
service:
  # port is the service port
  port: 8080

# serviceAccount is the configuration for the Kubernetes service account
serviceAccount:
  # create specifies whether a service account should be created
  create: true
  # name is the name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # annotations to add to the service account
  annotations: {}
  # automountServiceAccountToken is a boolean to determine if the service account token should be automatically mounted
  automountServiceAccountToken: true

# nats is the configuration for the NATS server
nats:
  # url is the URL of the NATS server
  url: nats://lfx-platform-nats.lfx.svc.cluster.local:4222

# opensearch is the configuration for the OpenSearch cluster
opensearch:
  # url is the URL of the OpenSearch cluster
  url: http://opensearch-cluster-master:9200

authelia:
  # enabled is a boolean to determine if the Authelia authenticator is enabled
  # Note: Disabling Authelia should only be used for local development
  enabled: true

# heimdall is the configuration for the heimdall middleware
heimdall:
  # enabled is a boolean to determine if the heimdall middleware is enabled
  # If disabled, there will be no authorization check on the query routes
  enabled: true
  add_middleware: false
  url: http://lfx-platform-heimdall.lfx.svc.cluster.local:4456

# Rate limiting configuration for org search endpoint
orgSearch:
  rateLimit:
    # enabled is a boolean to determine if rate limiting is enabled for org search
    enabled: true
    ## Token Bucket Behavior:
    # Bucket starts with: 30 tokens (full capacity)
    # Refill rate: 10 tokens per minute = 1 token every 6 seconds
    period: 1m
    # requestsPerMinute defines how many requests per minute are allowed per jwt token
    requestsPerMinute: 10
    # burstSize defines the maximum burst capacity (bucket size)
    burstSize: 30

# secret is the configuration for the Kubernetes Secret
secret:
  # name is the name of the secret
  name: lfx-v2-query-service-secrets
  # pageTokenSecret is the secret used for page token encryption
  # If not provided, a random 32-character secret will be generated
  # pageTokenSecret: "your-custom-secret-here"

jwks:
  url: http://lfx-platform-heimdall:4457/.well-known/jwks
jwt:
  signatureAlgorithm: PS256
