# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: Publish Main

'on':
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish Main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@v0.8
        with:
          version: v0.17.1
      - run: |
          ko build github.com/linuxfoundation/lfx-v2-query-service/cmd \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t ${{ github.sha }} \
            --sbom spdx
