# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: Publish Main

'on':
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish Main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10
        with:
          version: v0.17.1
      - name: Build and publish query service image
        env:
          VERSION: development
          GIT_COMMIT: ${{ github.sha }}
        run: |
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
          export BUILD_TIME
          GIT_COMMIT=${GIT_COMMIT:0:7}
          export GIT_COMMIT
          ko build github.com/linuxfoundation/lfx-v2-query-service/cmd \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t ${{ github.sha }} \
            -t development \
            --sbom spdx
