---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
name: License Header Check

"on": [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  license-header-check:
    name: License Header Check
    uses: linuxfoundation/lfx-public-workflows/.github/workflows/license-header-check.yml@c465d6571fa0b8be9d551d902955164ea04a00af
    with:
      copyright_line: "Copyright The Linux Foundation and each contributor to LFX."
      exclude_pattern: "gen/*"
