# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: "Query Service Build"

"on": [pull_request]

permissions:
  contents: read

jobs:
  build-pr:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod

      - name: Download Dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Test
        run: make test
