# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: "Query Service Build"

"on": [pull_request]

permissions:
  contents: read

jobs:
  build-pr:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version: stable

      - name: Download Dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test
